---
title: "Adopting Open-Source in Clinical Trial Reporting: Return on Investment"
format: html
toc: true
---

# Background

- brief intro of open-source adoption in clinical trial reporting
- Often driven by risk mitigation:
    - talent pool 
    - dynamic data viz
    - opportunity for cross-industry collaboration
    - interoperability (AI)
    - reduced vendor lock in

# Return on Investment

## End-user perspective
We could further split this into personas?   

Keeping it general for now: 

- develop transferable skills 
    - usage of industry-wide tools and languages such a git, R
    - adopt to modern ways of working (agile, best practices)

- contribute to the community
    - share your work publicly

## Business perspective

- Efficiency
    - reduced single-use code
    - shared development and shared maintenance (we could use some of James' material here on commits, issues)
    - Cross-functional synergy: using the same stack of tools across biometric and other computational functions (e.g. data science, real-world evidence) eases knowledge transfer and adds speed.
    - Increased agility through DevOps integration: Open source is better integrated with modern DevOps tools and practices. Access to key tools are often integrated into 
    packages for R and Python.
    - Reduced infrastructure costs: not only there is no licensing fees for R and Python, but there is better economics in how they integrate with diversity of modern tools such as data and compute resources, where SDKs are often most mature for open source languages.

- Quality
    - crowdsourced testing and issue tracking
    - pan-study code is seen by "many eyes"

- Talent
    - minimise upskilling as tools are shared across companies
    - mechanism for knowledge transfer
    - Deeper pull of talent: open source skills are more common in the workforce, making it easier to hire and retain talent.

- Transparency
    - tools are developed and evolve in the public domain



