# from: https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Render and Publish

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown

      - name: Render Quarto
        if: github.ref_name != 'main'  # render if not on main
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: slides

      - name: Render Quarto & Publish to GitHub Pages
        if: github.ref_name == 'main'  # render + deploy on main
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: presentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
